# Generated by Django 5.0.6 on 2024-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="city"),
        ),
    ]
